---
apiVersion: v1
kind: Pod
metadata: 
  name: gcp
spec: 
  containers:
    - name: cont-1
      image: nginx
      ports:
        - containerPort: 80
      resources:
        #requests:
         # memory: "64Mi"
          #cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"

        




