---
apiVersion: v1
kind: Pod
metadata: 
  name: gcp
spec: 
  containers:
    - name: cont-1
      image: nginx
      ports:
        - containerPort: 80
      resources:
        requests:
          memory: "5Mi"
          cpu: "10m"
        limits:
          memory: "12Mi" 
          cpu: "10m"