---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops

spec:
  replicas: 3
  selector: 
    matchLabels:
      app: swiggy
  template:
    metadata:
      labels:
        app: swiggy
    spec:
     containers:
       - name: cont-1
         image: shaikmustafa/cycle
         ports:
           - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: devops
spec:
  type: LoadBalancer
  selector:
    app: swiggy
  ports:
    - port: 80
      targetPort: 80
