---
apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  labels:
    env: dev
spec:
  containers:
    - name: cont-1
      image: nginx
      ports:
        - containerPort: 80



---
apiVersion: v1
kind: Service
metadata:
  name: flm-service2
spec:
  type: NodePort
  selector:
    env: dev
  ports:
    - port: 80
      targetPort: 80
      #nodeport:  
