---
apiVersion: v1
kind: PersistentVolume
metadata: 
  name: karthik
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  awsElasticBlockStore:
    volumeID: vol-0bbdc29b7fa37e51a
    fsType: ext4
