---
apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  labels:
    env: dev
spec:
  containers:
    - name: cont-1
      image: ubuntu
      ports:
        - containerPort: 80
      command: ["/bin/bash", "-c", "while true; do echo welcome to flm;  done"]
      volumeMounts:
        - name: flm-volume
          mountPath: "/tmp/devops"

    - name: cont-2
      image: ubuntu
      ports:
        - containerPort: 80
      command: ["/bin/bash", "-c", "while true; do echo welcome to flm;  done"]
      volumeMounts:
        - name: flm-volume
          mountPath: "/tmp/devops"


  volumes:
    - name: flm-volume
      hostPath:
        path: /tmp/data